# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-04-11 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import tweets.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20190410_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.TextField(max_length=140, validators=[tweets.validators.validate_content]),
        ),
    ]
