# Generated by Django 2.2 on 2019-05-04 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_tweet_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-timestamp']},
        ),
    ]
